### PR TITLE
Code complet + tests

### PR DESCRIPTION
**Pull request by QuentinAndre11**
La version de Loïc mais sans les modifications de l'upstream

### CODE REVIEW

**Review by massimotisi — CHANGES_REQUESTED** [review]
Not accepting because (as you can see in the "Files changed" tab of your pull request) you are changing files outside of your java package. To fix the problem:
- If the files or folders do not exist in the main repository, you can simply delete them
- If the files or folders exist in the main repository, you can replace them with the version from the main repository. To do that, right click on these files or folders -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository -> Replace. 

Then commit and push to your repository. 
If the files or folders are hidden in the Java perspective of Eclipse, you can go to the Resource perspective of Eclipse to see them.
Don't close this pull request, it will be automatically updated.

**Review by massimotisi — CHANGES_REQUESTED** [review]
Still the same problem

**Comment by massimotisi** [comment]
You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This has to list only files in your package.

**Comment by QuentinAndre11** [comment]
Si je comprends bien il me suffit de remplacer "this.quantitesLivrees " par "this.getQuantiteLivree()" ?

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "CACAO2020/CACAO2020" <CACAO2020@noreply.github.com>
Cc: "QuentinAndre11" <quentin.andre@imt-atlantique.net>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 29 Mai 2020 10:55:24
Objet: Re: [CACAO2020/CACAO2020] Code complet + tests (#45)

You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This has to list only files in your package.

**Comment by massimotisi** [comment]
In Eclipse, right click on all the packages that are not yours -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository -> Replace.
Then commit and push to your repository.

**Comment by QuentinAndre11** [comment]
Je ne comprends pas pourquoi est-ce qu'il me faut résoudre les conflits des autres équipes ?

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "CACAO2020/CACAO2020" <CACAO2020@noreply.github.com>
Cc: "QuentinAndre11" <quentin.andre@imt-atlantique.net>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 29 Mai 2020 11:04:15
Objet: Re: [CACAO2020/CACAO2020] Code complet + tests (#45)

Right click on all the packages that are not yours -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository -> Replace.
Then commit and push to your repository.

**Comment by massimotisi** [comment]
You are causing the conflict because you are sending modifications to the code of other teams. In particular you want to send to the main repository an old version of some files of the other teams.

**Comment by QuentinAndre11** [comment]
I replaced the "eq2producteur2" with the upstream version but one file created by loic remains I don't understand why... it's eq2Acteur

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "CACAO2020/CACAO2020" <CACAO2020@noreply.github.com>
Cc: "QuentinAndre11" <quentin.andre@imt-atlantique.net>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 29 Mai 2020 11:22:46
Objet: Re: [CACAO2020/CACAO2020] Code complet + tests (#45)

You are causing the conflict because you are sending modifications to the code of other teams. In particular you want to send to the main repository an old version of some files of the other teams,

**Comment by massimotisi** [comment]
Replace eq2producteur2 again, commit adding all the changed files, and push.

**Comment by QuentinAndre11** [comment]
Finally, it worked !
Thank you, have a nice day

----- Mail original -----
De: "Massimo Tisi" <notifications@github.com>
À: "CACAO2020/CACAO2020" <CACAO2020@noreply.github.com>
Cc: "QuentinAndre11" <quentin.andre@imt-atlantique.net>, "Author" <author@noreply.github.com>
Envoyé: Vendredi 29 Mai 2020 11:40:30
Objet: Re: [CACAO2020/CACAO2020] Code complet + tests (#45)

Merged #45 into master.

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/CACAO2020/CACAO2020/pull/45#event-3386433823

**Pull request merged**
