### PR TITLE
Dernière version

### PR DESCRIPTION
**Pull request by QuentinAndre11**
Version fonctionnelle

### CODE REVIEW

**Comment by massimotisi** [comment]
Not accepting because the code does not pass the tests. You can run the same tests on your Eclipse, they are `test/abstraction/FiliereParDefaultTest.java` and `test/presentation/FenetrePrincipaleTest.java`. To run them right-click on "build.xml", Run As -> Ant Build. You will see the error message in the console.

**Comment by massimotisi** [comment]
It looks like the same error that blocked the pull request of @CACAO2020/eq3transformateur1.
@CACAO2020/eq7distributeur2 any plan for it?

**Comment by lberthault** [comment]
@CACAO2020/eq4transformateur2 We tried something in our last pull, please try to pull it from upstream and tell us if it works.

**Comment by massimotisi** [comment]
@CACAO2020/eq7distributeur2 this pull request does not pass the test also after merging your latest pull request. You can see the error message here https://github.com/CACAO2020/CACAO2020/pull/86/checks?check_run_id=810454963 (Build with Ant)

**Comment by massimotisi** [comment]
@CACAO2020/eq7distributeur2 if the error is in your code, the only way to solve it is that you pull from @CACAO2020/eq4transformateur2, so you can run the test and try different fixes

**Comment by massimotisi** [comment]
Now it's better. Sometimes the test passes but sometimes it fails with this error:
    [junit] java.lang.NullPointerException
    [junit] 	at abstraction.eq6Distributeur1.DistributeurClientFinal.notificationRayonVide(DistributeurClientFinal.java:139)
    [junit] 	at abstraction.eq8Romu.clients.ClientFinal.next(ClientFinal.java:386)
    [junit] 	at abstraction.fourni.Filiere.next(Filiere.java:373)
    [junit] 	at abstraction.FiliereParDefaultTest.testNext(FiliereParDefaultTest.java:16)

@CACAO2020/eq6distributeur1 any idea?

**Comment by massimotisi** [comment]
@CACAO2020/eq6distributeur1 if the error is in your code, the only way to solve it is that you pull from @CACAO2020/eq4transformateur2, so you can run the test and try different fixes

**Pull request merged**
