### PR TITLE
V1 du code

### PR DESCRIPTION
**Pull request by melissatamine**

### CODE REVIEW

**Review by massimotisi — CHANGES_REQUESTED** [review]
You can't change the following files:
`src/presentation/FenetrePrincipale.java`
`src/abstraction/fourni/FiliereParDefaut.java`
`.classpath`
Please follow the same procedure for them.

**Comment by melissatamine** [comment]
@massimotisi I'm sorry but I cannot find the file ".classpath". Do you know where it is ?

**Comment by melissatamine** [comment]
And now that I removed these two files, an error appeared ! :(

**Comment by massimotisi** [comment]
For `.classpath` you have to go in the "Resource Perspective" of Eclipse (it is hidden in the Java perspective)
For the error, you need to correct it without touching files outside your package (I think you need to rename some classes)

**Pull request closed without merging**
