### PR TITLE
Most recent buyer and seller

### PR DESCRIPTION
**Pull request by MadRealm**

### CODE REVIEW

**Comment by MadRealm** [comment]
J'ai rajouté un commit qui modifie le fichier VenteContratCadre de l'équipe 2, car il y avait une erreur d'indice dans la méthode RefreshContrat, les tests run en local sur ma machine mais pas sur github

**Comment by massimotisi** [comment]
To run the test exactly like on the server, right-click on "build.xml", Run As -> Ant Build. You will see the error message in the console.

**Comment by massimotisi** [comment]
You can edit files of other teams if needed, but I will need their approval to accept the pull request. In any case the pull request will not be accepted if the tests do not run correctly.

**Comment by MadRealm** [comment]
I corrected the error from team 2 but now I'm getting errors because of the code from team 7, I think it's because the code I am trying to push is calling lines of code that weren't called before and therefore there is a nullpointer when I run the tests.
Though I don't know how to correct the error in the code from team 7 becauseI wouldn't want to change the behavior of their algorithm

**Comment by massimotisi** [comment]
I can't know if the error is in your code or the other teams' code. @CACAO2020/eq2producteur2 @CACAO2020/eq7distributeur2 any comment?

**Comment by lberthault** [comment]
Could you please give us the error log you get so we can check it? Thank you

**Comment by massimotisi** [comment]
[junit] java.lang.NullPointerException
    [junit] 	at abstraction.eq7Distributeur2.Stock.majPeremptionStock(Stock.java:122)
    [junit] 	at abstraction.eq7Distributeur2.Stock.retirerStockChocolat(Stock.java:162)
    [junit] 	at abstraction.eq7Distributeur2.Vendeur.vendre(Vendeur.java:383)
    [junit] 	at abstraction.eq7Distributeur2.Distributeur2.vendre(Distributeur2.java:398)
    [junit] 	at abstraction.eq8Romu.clients.ClientFinal.next(ClientFinal.java:383)
    [junit] 	at abstraction.fourni.Filiere.next(Filiere.java:373)
    [junit] 	at abstraction.FiliereParDefaultTest.testNext(FiliereParDefaultTest.java:16)

**Comment by MadRealm** [comment]
Sure here it is : 
image

**Comment by lprzybylski59** [comment]
The changes in our code isn't a problem, we wanted to do it ourselves but we were too slow sorry

**Comment by lberthault** [comment]
We tried something, we have no error locally. Is it resolved?
It looks so. Thank you!

**Comment by massimotisi** [comment]
After I reverted this pull request, you forgot to send me again the fixes to the following files:
- src/abstraction/eq3Transformateur1/Stock.java
- src/abstraction/eq3Transformateur1/Tresorerie.java
- src/abstraction/eq3Transformateur1/VendeurChocolat.java

It's just grammar fixes, you can see them here: https://github.com/CACAO2020/CACAO2020/pull/75/files 
If you want, you can include them in a new pull request.

**Comment by MadRealm** [comment]
Yes I was aware that I didn't change them again but as they typos I decided it wasn't important to commit them

**Pull request merged**
