### PR TITLE
pull request avec trop de fichiers modifiés

### PR DESCRIPTION
**Pull request by kristofszentes**

### CODE REVIEW

**Review by massimotisi — CHANGES_REQUESTED** [review]
Not accepting because (as you can see in the "Files changed" tab of your pull request) you are changing files outside of your java package. To remove those changes in Eclipse, right click on these files or packages -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select my repository -> Replace. Then commit and push to your repository. If the files are hidden in the Java perspective of Eclipse, you can go to the Resource perspective of Eclipse to see them.

**Comment by kristofszentes** [comment]
I saw that, I only created this Pull request so that Romuald could see what files were changed, do you think I will also be able to replace the .metadata files with the ones from the upstream ?

**Comment by massimotisi** [comment]
In the Resource perspective you can replace all folders and files (including hidden files). Since there is no `.metadata` folder in the main repository, you don't have anything to replace it with. You can simply delete it.

**Comment by kristofszentes** [comment]
Ok, thank you.

**Pull request merged**
